const img1 =
  "https://img.freepik.com/premium-photo/plagued-melodies-enigmatic-kenku-bard-aboard-crimson-avenger_983420-173057.jpg?size=626&ext=jpg&ga=GA1.1.109111083.1672218237&semt=sph";
const img2 =
  "https://img.freepik.com/premium-photo/captivating-imagery-dynamic-army-avenger-exudes-authenticity-with-his-jetblack-hair-blue-toy-g_983420-172748.jpg?size=626&ext=jpg&ga=GA1.1.109111083.1672218237&semt=sph";
const img3 =
  "https://img.freepik.com/free-photo/male-boxer-boxing-punching-bag_155003-6125.jpg?size=626&ext=jpg&ga=GA1.1.109111083.1672218237&semt=sph";
const img4 =
  "https://img.freepik.com/free-photo/young-attractive-female-boxer-with-long-hair-boxing-gloves-is-ready-fight_613910-11583.jpg?size=626&ext=jpg&ga=GA1.1.109111083.1672218237&semt=sph";

let getHookedAgents = [
  {
    email: "user1@example.com",
    password: "password1",
    name: "John",
    surname: "Doe",
    nickname: "johnny",
    profileImage: img1,
    category: "boxer",
    aboutUser: "left right center baby 😂🤣",
    status: "offline",
    PostsArray: [
      {
        id: 0,
        category: "video",
        src: [img2],
        timeStamp: "2 October 2023",
        text: "who lives, who dies? Who picks them weights? 🤐",
        likes: 1223,
        comments: 223,
        commentsArr: [
          {
            id: 1,
            src: img3,
            name: "Andrew Hunger Thomsom",
            comment: "I love you 😍",
            timeStamp: "12:34",
          },
          {
            id: 2,
            src: img1,
            name: "Andrew Hunger Thomsom",
            comment: "I love you, you are my heroooo!!! 😍",
            timeStamp: "12:34",
          },
          {
            id: 2,
            src: img2,
            name: "Andrew Hunger Thomsom",
            comment: "😍",
            timeStamp: "12:34",
          },
        ],
      },
    ],

    Profile: {
      Records: "17-23-12",
      Height: "176",
      Gender: "male",
      KO: 3,
      Age: 23,
      Weight: 67,
      skills: ["punching", "skipping", "shadow boxing"],
      achievements: ["golden gloves", "School boy champion"],
      goals: [
        "fast leg movements",
        "strong body punches",
        "stamina",
        "sparring for 12 rounds",
      ],
    },
    Connections: [
      "user2@example.com",
      "user3@example.com",
      "user4@example.com",
    ],
    Messages: [],
  },
  {
    email: "user2@example.com",
    password: "password2",
    name: "Jane",
    surname: "Doe",
    nickname: "jane",
    profileImage: img2,
    category: "boxer",
    aboutUser: "hitting it one jab at a time 🔥",
    status: "offline",
    PostsArray: [],
    Profile: {
      Records: "17-23-12",
      Height: "176",
      Gender: "female",
      KO: 8,
      Age: 20,
      Weight: 60,
      skills: [
        "Straight Punches",
        "Uppercuts",
        "Strong left hook",
        "Leg movement/footwork",
      ],
      achievements: [
        "Golden Gloves",
        "SA champion 4X",
        "Olympic gold medalist",
      ],
      goals: [
        "ChampionShips",
        "Schooboy",
        "Fast leg movement",
        "Strong body punches",
        "Moving forward",
        "Sneak jabs",
        "Fitness",
        "Stamina gain",
        "Speed increase",
        "Breathing properly",
      ],
    },
    Connections: ["user1@example.com", "user3@example.com"],
    Messages: [],
  },
  {
    email: "user3@example.com",
    password: "password3",
    name: "Bob",
    surname: "Smith",
    nickname: "bob",
    profileImage: img3,
    category: "boxer",
    aboutUser: "step aside 😙😚🙂",
    status: "offline",
    PostsArray: [],
    Profile: {
      skills: ["punching", "skipping", "shadow boxing"],
      achievements: ["golden gloves", "School boy champion"],
      goals: [
        "fast leg movements",
        "strong body punches",
        "stamina",
        "sparring for 12 rounds",
      ],
    },
    Connections: ["user2@example.com", "user4@example.com"],
    Messages: [],
  },
  {
    email: "user4@example.com",
    password: "password4",
    name: "Alice",
    surname: "Johnson",
    nickname: "alice",
    profileImage: img4,
    category: "boxer",
    aboutUser: "bring it on hommie 👨🏾‍🦲",
    status: "offline",
    PostsArray: [],
    Profile: {
      skills: ["punching", "skipping", "shadow boxing"],
      achievements: ["golden gloves", "School boy champion"],
      goals: [
        "fast leg movements",
        "strong body punches",
        "stamina",
        "sparring for 12 rounds",
      ],
    },
    Connections: ["user3@example.com", "user5@example.com"],
    Messages: [],
  },
  {
    email: "user5@example.com",
    password: "password5",
    name: "Charlie",
    surname: "Brown",
    nickname: "charlie",
    profileImage: img3,
    category: "coach",
    aboutUser: "This is what we do! 👩🏾‍🦰👨🏾‍🦰",
    status: "offline",
    PostsArray: [],
    Profile: {
      skills: ["punching", "skipping", "shadow boxing"],
      achievements: ["golden gloves", "School boy champion"],
      goals: [
        "fast leg movements",
        "strong body punches",
        "stamina",
        "sparring for 12 rounds",
      ],
    },
    Connections: [],
    Messages: [],
  },
  {
    email: "user6@example.com",
    password: "password",
    name: "Eva",
    surname: "Miller",
    nickname: "eva",
    profileImage: img2,
    category: "coach",
    aboutUser: "bring hope to the inner city",
    status: "offline",
    PostsArray: [],
    Profile: {
      skills: ["punching", "skipping", "shadow boxing"],
      achievements: ["golden gloves", "School boy champion"],
      goals: [
        "fast leg movements",
        "strong body punches",
        "stamina",
        "sparring for 12 rounds",
      ],
    },
    Connections: [],
    Messages: [],
  },
  {
    email: "user7@example.com",
    password: "password7",
    name: "David",
    surname: "Lee",
    nickname: "david",
    profileImage: img3,
    category: "coach",
    aboutUser: "letting it slide...",
    status: "offline",
    PostsArray: [],
    Profile: {
      skills: ["punching", "skipping", "shadow boxing"],
      achievements: ["golden gloves", "School boy champion"],
      goals: [
        "fast leg movements",
        "strong body punches",
        "stamina",
        "sparring for 12 rounds",
      ],
    },
    Connections: [],
    Messages: [],
  },
  {
    email: "user8@example.com",
    password: "password8",
    name: "Grace",
    surname: "Taylor",
    nickname: "grace",
    profileImage: img2,
    category: "coach",
    aboutUser: "Dang",
    status: "offline",
    PostsArray: [],
    Profile: {
      skills: ["punching", "skipping", "shadow boxing"],
      achievements: ["golden gloves", "School boy champion"],
      goals: [
        "fast leg movements",
        "strong body punches",
        "stamina",
        "sparring for 12 rounds",
      ],
    },
    Connections: [],
    Messages: [],
  },
  {
    email: "user9@example.com",
    password: "password9",
    name: "Sam",
    surname: "Wilson",
    nickname: "sam",
    profileImage: img1,
    category: "coach",
    aboutUser: "About sam... 😂😎",
    status: "offline",
    PostsArray: [],
    Profile: {
      skills: ["punching", "skipping", "shadow boxing"],
      achievements: ["golden gloves", "School boy champion"],
      goals: [
        "fast leg movements",
        "strong body punches",
        "stamina",
        "sparring for 12 rounds",
      ],
    },
    Connections: [],
    Messages: [],
  },
];
module.exports = getHookedAgents;
